name: approxcv
channels:
  - conda-forge
  - ankurankan 
dependencies:
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - conda-forge::autograd
  - conda-forge::matplotlib
  - conda-forge::tqdm 
  - ankurankan::pgmpy

